name: bleau_todo_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' # Menggunakan rentang SDK yang lebih luas untuk kompatibilitas

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  hive: ^2.1.0         # Versi Hive yang lebih stabil dan teruji
  hive_flutter: ^1.1.0 # Versi Hive Flutter yang lebih stabil dan teruji
  table_calendar: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  hive_generator: ^1.1.3 # Versi hive_generator yang sesuai dengan Hive ^2.1.0
  build_runner: ^2.1.8 # Versi build_runner yang lebih lama dan sering stabil
  analyzer: ^4.7.0     # <--- VERSI ANALYZER YANG SUDAH KITA SESUAIKAN DENGAN hive_generator ^1.1.3

flutter:
  uses-material-design: true

  assets:
    - assets/images/